services:
  - type: web
    name: watchtracker
    buildCommand: "mvn clean package -DskipTests"
    startCommand: "java -jar target/watchtracker-0.0.1-SNAPSHOT.jar"
    plan: free
    region: oregon
